version: '2'
services:
  yoothit-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/yoothit/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=yoothit
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
