/**
 * The >LogAction enumeration.
 */
export enum LogAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  ARCHIVE = 'ARCHIVE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  AUTHENTICATE = 'AUTHENTICATE',
  VIEW = 'VIEW',
  ACTIVATE = 'ACTIVATE',
}
